"""add kpi_link_cycle table

Revision ID: 11d018484810
Revises: 6531ddb496d2
Create Date: 2026-07-13 11:19:22.117945

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11d018484810"
down_revision: str | None = "6531ddb496d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_link_cycle",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_key", sa.String(), nullable=False),
        sa.Column(
            "member_kpi_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "member_link_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("judge_goal_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["judge_goal_id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kpi_link_cycle_canonical_key"), "kpi_link_cycle", ["canonical_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kpi_link_cycle_canonical_key"), table_name="kpi_link_cycle")
    op.drop_table("kpi_link_cycle")
    # ### end Alembic commands ###
