"""add goal.parent_id

Revision ID: 20cd74dc490c
Revises: febf4b29d074
Create Date: 2026-07-08 15:07:50.817292

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20cd74dc490c"
down_revision: str | None = "febf4b29d074"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite can't ALTER a table to add a FK constraint outside of batch mode
    # (copy-and-move strategy), unlike the other dialects autogenerate assumes.
    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_goal_parent_id"), ["parent_id"], unique=False)
        batch_op.create_foreign_key("fk_goal_parent_id_entity", "entity", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.drop_constraint("fk_goal_parent_id_entity", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_goal_parent_id"))
        batch_op.drop_column("parent_id")
    # ### end Alembic commands ###
