"""add kpi_factor table

Revision ID: 338ffd927507
Revises: 11d018484810
Create Date: 2026-07-13 11:51:58.809125

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "338ffd927507"
down_revision: str | None = "11d018484810"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_factor",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("composite_kpi_id", sa.String(length=36), nullable=False),
        sa.Column("factor_kpi_id", sa.String(length=36), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["composite_kpi_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["factor_kpi_id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kpi_factor_composite_kpi_id"), "kpi_factor", ["composite_kpi_id"], unique=False)
    op.create_index(op.f("ix_kpi_factor_factor_kpi_id"), "kpi_factor", ["factor_kpi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kpi_factor_factor_kpi_id"), table_name="kpi_factor")
    op.drop_index(op.f("ix_kpi_factor_composite_kpi_id"), table_name="kpi_factor")
    op.drop_table("kpi_factor")
    # ### end Alembic commands ###
