"""add kpi_link table

Revision ID: 6531ddb496d2
Revises: 20cd74dc490c
Create Date: 2026-07-08 20:00:34.509620

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6531ddb496d2"
down_revision: str | None = "20cd74dc490c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_link",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_kpi_id", sa.String(length=36), nullable=False),
        sa.Column("target_kpi_id", sa.String(length=36), nullable=False),
        sa.Column("link_type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_kpi_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_kpi_id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kpi_link_source_kpi_id"), "kpi_link", ["source_kpi_id"], unique=False)
    op.create_index(op.f("ix_kpi_link_target_kpi_id"), "kpi_link", ["target_kpi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kpi_link_target_kpi_id"), table_name="kpi_link")
    op.drop_index(op.f("ix_kpi_link_source_kpi_id"), table_name="kpi_link")
    op.drop_table("kpi_link")
    # ### end Alembic commands ###
