"""add goal table

Revision ID: 96083dc962bc
Revises: 83ee12f111f6
Create Date: 2026-07-08 11:05:05.406247

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96083dc962bc"
down_revision: str | None = "83ee12f111f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goal",
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("role_label", sa.String(length=20), nullable=False),
        sa.Column("kpis", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("is_backlog", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("goal")
    # ### end Alembic commands ###
