"""add goal deadline importance urgency

Revision ID: a205b73f05ad
Revises: 064d0e836915
Create Date: 2026-07-22 11:14:43.614528

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a205b73f05ad"
down_revision: str | None = "064d0e836915"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goal", sa.Column("deadline", sa.Date(), nullable=True))
    op.add_column("goal", sa.Column("importance", sa.Boolean(), nullable=True))
    op.add_column("goal", sa.Column("urgency", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goal", "urgency")
    op.drop_column("goal", "importance")
    op.drop_column("goal", "deadline")
    # ### end Alembic commands ###
