"""add kpi entity, drop goal.kpis json

Revision ID: febf4b29d074
Revises: 96083dc962bc
Create Date: 2026-07-08 14:47:20.965485

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "febf4b29d074"
down_revision: str | None = "96083dc962bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi",
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("goal_id", sa.String(length=36), nullable=False),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"]),
        sa.ForeignKeyConstraint(["goal_id"], ["entity.id"]),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index(op.f("ix_kpi_goal_id"), "kpi", ["goal_id"], unique=False)
    # No data migration: dev has no rows carrying goal.kpis at this point in the branch history.
    op.drop_column("goal", "kpis")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goal",
        sa.Column(
            "kpis",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_kpi_goal_id"), table_name="kpi")
    op.drop_table("kpi")
    # ### end Alembic commands ###
